### ISSUE TITLE
Roadmap 0.1.0

### ISSUE THREAD

**Issue by mphasize** [mphasize/sails-generate-ember-blueprints#17]
- [x] merge PR #9 
- [ ] add some tests, for example if proper configuration options are set
- [ ] add examples and explain all the configuration options and their impact
- [ ] adjust default behavior of advanced to emulate `basic`, unify the 2 sets
- [ ] respect non-default settings for `primaryKey` on Sails models
- [ ] simplify `Ember` service to always use sideloading (embedded style will be a separate set of blueprints)
- [ ] bring the require lodash improvements from the basic blueprints into the advanced blueprints

The work being done can be coordinated here #19

**Comment by Globegitter** [comment]
@mphasize So the only thing here really is just missing tests for mongodb?

**Comment by mphasize** [comment]
Actually, a simple human trying the new blueprints on a Sails installation with Mongo would be test enough for me for now, since real tests are still missing anyway (but I don't consider those a blocker atm).

**Comment by Globegitter** [comment]
Ok I will factor in some time this week for that. Can't promise today, but will do. Will actually be quite easy, just using `sane new testproject -d mongo --docker` :)

**Comment by mphasize** [comment]
I have to admit, that I still have to try Sane... didn't get around to it yet. /ducks

**Comment by Globegitter** [comment]
Haha no worries, I am sure you'll get around to it at some point.

**Comment by mphasize** [comment]
@Globegitter Among the PRs on the original Sails repo I've just seen a couple of interesting things especially concerning the blueprints. Maybe we can adapt some of the things for these blueprints...
- https://github.com/balderdashy/sails/pull/2450
- https://github.com/balderdashy/sails/pull/2435
- https://github.com/balderdashy/sails/pull/2445

**Comment by Globegitter** [comment]
@mphasize just needing embedded support. Was that part of any of the current plans? Is that supposed to be possible now? I can't quite remember if we talked about that before.

**Comment by Globegitter** [comment]
Aahh should read the README myself :P

**Comment by listepo** [comment]
what status version 0.1.0?

**Comment by listepo** [comment]
It would be useful https://github.com/tjwebb/marlinspike
